name: Tests with a database PHP8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-20.04
    name: "Running Integration tests for PHP ${{ matrix.php-version }} on Neo4j ${{ matrix.neo4j-version }}"
    strategy:
      fail-fast: false
      matrix:
        neo4j-version: ["4.3", "4.4", "5.1", "5.2"]
        php-version: ['8.0', '8.1']

    services:
      neo4j:
        image: neo4j:${{ matrix.neo4j-version }}
        env:
          NEO4J_AUTH: neo4j/nothing
          NEO4JLABS_PLUGINS: '["apoc"]'
        ports:
          - 7687:7687
          - 7474:7474
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, sockets
          coverage: xdebug
          ini-values: max_execution_time=0

      - name: Install dependencies
        run: composer install --no-progress

      - name: Test with phpunit
        run: vendor/bin/phpunit --configuration phpunit.xml --testsuite "Database"
