name: Tests without a database PHP7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: "Running Tests for PHP ${{ matrix.php-version }}"
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.1', '7.2', '7.3', '7.4']

    steps:
      - uses: actions/checkout@v3
      - run: composer validate --strict
      - uses: php-actions/composer@v6
        with:
          progress: yes
          php_version: ${{ matrix.php-version }}
          version: 2
      - uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml
          version: 7
          php_version: ${{ matrix.php-version }}
          args: --testsuite "NoDatabase"
